### ISSUE TITLE
ERROR function get_locality_filter

### ISSUE THREAD

**Issue by support-site** [martinjack/Intime3#1]
**public function get_locality_filter($data = array())**
$argv['get_locality_filtered']['district_id']   = isset($data['district_name']) ? strlen($data['district_name']) > 0 ? $data['district_name'] : '' : '';
**заменить  на** 
$argv['get_locality_filtered']['district_id']   = isset($data['district_id']) ? strlen($data['district_id']) > 0 ? $data['district_id'] : '' : '';

**Comment by martinjack** [comment]
fix https://github.com/martinjack/Intime3/blob/7faba30af0fda12a2b3b8232c7a66a6036a7430f/src/InTime3.php#L312
