### ISSUE TITLE
Не работает метод get_locality_list()

### ISSUE THREAD

**Issue by hellerandrei** [martinjack/Intime3#2]
Добрый день. 
Почему то не работает get_locality_list()
Все остальные методы работают.  После вызова идет задержка, но данные не приходят и ошибку найти не получается. Уже все перепробовал :(

**Comment by martinjack** [comment]
Доброго. Работает нормально. Загружает просто долго. Если также не будет работать, советую использовать метод [get_locality_filter](https://github.com/martinjack/Intime3#get_locality_filterdata--array)
![Снимок экрана от 2019-03-23 22-51-36](https://user-images.githubusercontent.com/11950689/54871542-53689a80-4dbe-11e9-9906-1c65629147ac.png)

**Comment by hellerandrei** [comment]
Спасибо за ответ. Может можно где-то таймаут установить на большее значение, потому как у меня через 12 секунд обрывает. Хотел бы по этому методу записывать все города в Базу. 
В chrome вернуло: Cannot resume an already running generator in <b>Unknown</b> on line <b>0</b><br />

**Comment by hellerandrei** [comment]
Нашел, проблема оказалась в версии php 5.6.39, изменил на 7.0.33 и все загрузилось.

**Comment by martinjack** [comment]
Даже так , интересно. 
[Новую версию выпустил](https://github.com/martinjack/Intime3/releases/tag/1.2)
добавил тайм-аут на подключение и на возврат.

**Comment by hellerandrei** [comment]
Спасибо за вашу работу, проверил сегодня на 5.6.39 работает.
