### ISSUE TITLE
Вопрос по созданию электронной ТТН

### ISSUE THREAD

**Issue by hellerandrei** [martinjack/Intime3#5]
Добрый день. 
Пытаюсь создать ТТН. Отправляю данные метод [ declaration_insert_update ], но получаю ошибку - "ERROR-Не вказано місця"
Уже все перепробовал, подскажите в каком виде передавать данные в элементе (seats)
![Screenshot_30](https://user-images.githubusercontent.com/31564134/75194643-30c6ca80-5761-11ea-85d5-db654243e88c.jpg)
и так ![Screenshot_31](https://user-images.githubusercontent.com/31564134/75195343-6a4c0580-5762-11ea-98f6-e9ea529bca11.jpg)
И еще момент. Сервер выдавал ошибку (Неправильный данные склада отправителя), пока не передал вместо https://github.com/martinjack/Intime3/blob/6eda8cc31360ea1239ca89ee05ac1a1502b7ea17/src/InTime3.php#L512 **sender_warehouse_id** 

Спасибо.

**Comment by martinjack** [comment]
Доброго. Да,  спасибо исправил. :+1:

**Comment by martinjack** [comment]
Как добавить место описано в документации:
Добавил метод **createSeat**, просто передайте список параметров

![Снимок экрана от 2020-02-25 11-56-06](https://user-images.githubusercontent.com/11950689/75236933-30f9b100-57c7-11ea-86b4-d45f2de15dbb.png)

**Comment by hellerandrei** [comment]
Не получается :( Не могу понять где моя ошибка.
Отправляю:
```
$seat = array();
$seat['Goods_type_id'] = 1;  // Посылка
$seat['Weight_m'] = 30;
$seat['Length_m'] = 35;
$seat['Width_m'] = 27;
$seat['Height_m'] = 40;
$seat['Weight_r'] = 0;
$seat['Gsize_r'] = 0;
$seat['Count_m'] = 1;	
$seat['Goods_type_descr_id']  = 155; // Семена
$seat['Box_id'] = 0;
$seat['SN'] = '';				
				
$seats = $intime->createSeat($seat);
```
Данные взял из прочитанной с помощью api созданной на складе  работником компании ТТН

Выдает ошибку : "ERROR-Не вказано місця"
![Screenshot_36](https://user-images.githubusercontent.com/31564134/75258413-13d8d880-57ef-11ea-98a1-24f433f54cb1.jpg)

А вот если отправлять 
```
$seats = '<SEATS>
<SEAT>
<GOODS_TYPE_ID>1</GOODS_TYPE_ID><GOODS_TYPE_DESCR_ID>155</GOODS_TYPE_DESCR_ID>
<WEIGHT_M>30</WEIGHT_M>
<LENGTH_M>35</LENGTH_M>
<WIDTH_M>27</WIDTH_M>
<HEIGHT_M>40</HEIGHT_M>
<COUNT_M>1</COUNT_M>
</SEAT>
</SEATS>';  
```
Сервер уже отвечает например, что не правильное описание места. 
![Screenshot_38](https://user-images.githubusercontent.com/31564134/75259429-b3e33180-57f0-11ea-9e37-d421f0955052.jpg)

Но вот если все указать правильно, возвращает вместо "ок" пустой результат и в кабинете ТТН не создает... 
![Screenshot_39](https://user-images.githubusercontent.com/31564134/75259576-e725c080-57f0-11ea-936c-68b21666a97e.jpg)

**Comment by martinjack** [comment]
Хм.. Чуть позже гляну , что не так

**Comment by hellerandrei** [comment]
получил ТТН  
![Screenshot_40](https://user-images.githubusercontent.com/31564134/75260208-f0635d00-57f1-11ea-9b06-21d2683cda75.jpg)

Отправив:
```
$seats = '<SEATS>
<SEAT>
<GOODS_TYPE_ID>1</GOODS_TYPE_ID><GOODS_TYPE_DESCR_ID>155</GOODS_TYPE_DESCR_ID>
<WEIGHT_M>30</WEIGHT_M>
<LENGTH_M>35</LENGTH_M>
<WIDTH_M>27</WIDTH_M>
<HEIGHT_M>40</HEIGHT_M>
<COUNT_M>1</COUNT_M>
</SEAT>
</SEATS>'; 
```
Достучался до тех поддержки, сказали убрать поле cash_on_delivery_sum

Но если отправляю через:
```
$seat = array();
$seat['Goods_type_id'] = 1;  // Посылка
$seat['Weight_m'] = 30;
$seat['Length_m'] = 35;
$seat['Width_m'] = 27;
$seat['Height_m'] = 40;
$seat['Weight_r'] = 0;
$seat['Gsize_r'] = 0;
$seat['Count_m'] = 1;	
$seat['Goods_type_descr_id']  = 155; // Семена
$seat['Box_id'] = 0;
$seat['SN'] = '';				
				
$seats = $intime->createSeat($seat);
```
![Screenshot_41](https://user-images.githubusercontent.com/31564134/75260556-754e7680-57f2-11ea-8d6c-c97010a16ac8.jpg)

**Comment by hellerandrei** [comment]
Ответ от поддержки, по поводу отправки данных JSON . -

> > Нажаль, існує проблема з заповненням та відправкою даних полів блоку seats. Проблема на усуненні. Вибачте за незручності 

Спасибо за потраченное время и помощь. Если появится от них еще информация, я напишу.
