### ISSUE TITLE
Просмотр информации по ТТН

### ISSUE THREAD

**Issue by hellerandrei** [martinjack/Intime3#6]
Добрый день. 
Заметил еще что интайм поменял в api вызов для проверки ttn
https://github.com/martinjack/Intime3/blob/592ffeefbb9c3281f6fdface80b7080e23648fee/src/InTime3.php#L708
на
$argv['info_tn']['decl_num'] = $number;

**Comment by martinjack** [comment]
Да, спасибо. Исправил :+1:
